//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template: Logisch Ontwerp BRP 4.2.0 1 januari 2023
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;

namespace Centric.PIV.Burgerzaken.RaadplegenPL.ResourceLayer.Brp.DomainModel.LogischOntwerp.LandelijkeTabellen
{
	/// <summary>
	/// Representeert Element0511 (Nationaliteitscode)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0511 : Element<Int16>
	{
		private Element0511() => this.element = new ElementNummer(nummer: "0511", naam: "Nationaliteitscode");
		public Element0511(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element0511(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element0512 (Officiële omschrijving nationaliteit)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0512 : Element<String>
	{
		private Element0512() => this.element = new ElementNummer(nummer: "0512", naam: "Officiële omschrijving nationaliteit");
		public Element0512(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element9998 (Datum ingang tabelregel)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9998 : Element<Int32>
	{
		private Element9998() => this.element = new ElementNummer(nummer: "9998", naam: "Datum ingang tabelregel");
		public Element9998(Int32 val) : this() => this.waarde = new ElementWaarde<Int32> { Waarde = val };
		public Element9998(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int32> { Waarde = Convert.ToInt32(val) };
		}
	}

	/// <summary>
	/// Representeert Element9999 (Datum beëindiging tabelregel)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9999 : Element<Int32>
	{
		private Element9999() => this.element = new ElementNummer(nummer: "9999", naam: "Datum beëindiging tabelregel");
		public Element9999(Int32 val) : this() => this.waarde = new ElementWaarde<Int32> { Waarde = val };
		public Element9999(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int32> { Waarde = Convert.ToInt32(val) };
		}
	}

	/// <summary>
	/// Representeert Element9210 (Gemeentecode)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9210 : Element<string>
	{
		private Element9210() => this.element = new ElementNummer(nummer: "9210", naam: "Gemeentecode");
		public Element9210(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element9210(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element9211 (Officiële gemeentenaam)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9211 : Element<String>
	{
		private Element9211() => this.element = new ElementNummer(nummer: "9211", naam: "Officiële gemeentenaam");
		public Element9211(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element9212 (Nieuwe gemeentecode)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9212 : Element<Int16>
	{
		private Element9212() => this.element = new ElementNummer(nummer: "9212", naam: "Nieuwe gemeentecode");
		public Element9212(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element9212(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element9410 (Landcode)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9410 : Element<Int16>
	{
		private Element9410() => this.element = new ElementNummer(nummer: "9410", naam: "Landcode");
		public Element9410(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element9410(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element9411 (Officiële landnaam)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9411 : Element<String>
	{
		private Element9411() => this.element = new ElementNummer(nummer: "9411", naam: "Officiële landnaam");
		public Element9411(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element0231 (Voorvoegsel)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0231 : Element<String>
	{
		private Element0231() => this.element = new ElementNummer(nummer: "0231", naam: "Voorvoegsel");
		public Element0231(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element9610 (Reden opnemen/beëindigen nationaliteit)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9610 : Element<Int16>
	{
		private Element9610() => this.element = new ElementNummer(nummer: "9610", naam: "Reden opnemen/beëindigen nationaliteit");
		public Element9610(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element9610(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element9620 (Omschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9620 : Element<String>
	{
		private Element9620() => this.element = new ElementNummer(nummer: "9620", naam: "Omschrijving");
		public Element9620(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element9630 (Soort)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element9630 : Element<String>
	{
		private Element9630() => this.element = new ElementNummer(nummer: "9630", naam: "Soort");
		public Element9630(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element0221 (Adellijke titel/predicaat)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0221 : Element<String>
	{
		private Element0221() => this.element = new ElementNummer(nummer: "0221", naam: "Adellijke titel/predicaat");
		public Element0221(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element0222 (Omschrijving adellijke titel/predicaat)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0222 : Element<String>
	{
		private Element0222() => this.element = new ElementNummer(nummer: "0222", naam: "Omschrijving adellijke titel/predicaat");
		public Element0222(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element0223 (Soort)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0223 : Element<String>
	{
		private Element0223() => this.element = new ElementNummer(nummer: "0223", naam: "Soort");
		public Element0223(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element8121 (Akteaanduiding)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element8121 : Element<String>
	{
		private Element8121() => this.element = new ElementNummer(nummer: "8121", naam: "Akteaanduiding");
		public Element8121(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element8122 (Omschrijving soort akte)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element8122 : Element<String>
	{
		private Element8122() => this.element = new ElementNummer(nummer: "8122", naam: "Omschrijving soort akte");
		public Element8122(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element0741 (Reden ontbinding/nietigverklaring huwelijk/geregistreerd)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0741 : Element<String>
	{
		private Element0741() => this.element = new ElementNummer(nummer: "0741", naam: "Reden ontbinding/nietigverklaring huwelijk/geregistreerd");
		public Element0741(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element0742 (Omschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element0742 : Element<String>
	{
		private Element0742() => this.element = new ElementNummer(nummer: "0742", naam: "Omschrijving");
		public Element0742(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3511 (Nederlands reisdocument)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3511 : Element<String>
	{
		private Element3511() => this.element = new ElementNummer(nummer: "3511", naam: "Nederlands reisdocument");
		public Element3511(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3512 (Omschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3512 : Element<String>
	{
		private Element3512() => this.element = new ElementNummer(nummer: "3512", naam: "Omschrijving");
		public Element3512(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3541 (Autoriteit van afgifte)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3541 : Element<String>
	{
		private Element3541() => this.element = new ElementNummer(nummer: "3541", naam: "Autoriteit van afgifte");
		public Element3541(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3542 (Omschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3542 : Element<String>
	{
		private Element3542() => this.element = new ElementNummer(nummer: "3542", naam: "Omschrijving");
		public Element3542(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3911 (Verblijfstitel)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3911 : Element<Int16>
	{
		private Element3911() => this.element = new ElementNummer(nummer: "3911", naam: "Verblijfstitel");
		public Element3911(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element3911(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element3912 (Omschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3912 : Element<String>
	{
		private Element3912() => this.element = new ElementNummer(nummer: "3912", naam: "Omschrijving");
		public Element3912(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element8811 (Code RNI-deelnemer)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element8811 : Element<Int16>
	{
		private Element8811() => this.element = new ElementNummer(nummer: "8811", naam: "Code RNI-deelnemer");
		public Element8811(Int16 val) : this() => this.waarde = new ElementWaarde<Int16> { Waarde = val };
		public Element8811(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<Int16> { Waarde = Convert.ToInt16(val) };
		}
	}

	/// <summary>
	/// Representeert Element8812 (Omschrijving RNI-deelnemer)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element8812 : Element<String>
	{
		private Element8812() => this.element = new ElementNummer(nummer: "8812", naam: "Omschrijving RNI-deelnemer");
		public Element8812(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3211 (Gezagsverhouding)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3211 : Element<String>
	{
		private Element3211() => this.element = new ElementNummer(nummer: "3211", naam: "Gezagsverhouding");
		public Element3211(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}

	/// <summary>
	/// Representeert Element3212 (Omschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public partial class Element3212 : Element<String>
	{
		private Element3212() => this.element = new ElementNummer(nummer: "3212", naam: "Omschrijving");
		public Element3212(string val) : this()
		{
			if (val.Length > 0) this.waarde = new ElementWaarde<String> { Waarde = Convert.ToString(val) };
		}
	}
}
