//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template: Logisch Ontwerp BRP 4.2.0 1 januari 2023
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;

namespace Centric.PIV.Burgerzaken.RaadplegenPL.ResourceLayer.Brp.DomainModel.LogischOntwerp.LandelijkeTabellen
{
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel32(Nationaliteitentabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel32
	{
		/// <summary>
		/// Representeert Element0511
		/// Nationaliteitscode
		/// </summary>
		[JsonProperty("Element0511")]
		public Element0511 element0511 { get; set; }

		/// <summary>
		/// Representeert Element0512
		/// Officiële omschrijving nationaliteit
		/// </summary>
		[JsonProperty("Element0512")]
		public Element0512 element0512 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public Int16 Code => element0511.Waarde;

		[JsonIgnore]
		public string Omschrijving => element0512.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel32(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element0511 = new Element0511(columns[0]);
			element0512 = new Element0512(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel33(Gemeententabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel33
	{
		/// <summary>
		/// Representeert Element9210
		/// Gemeentecode
		/// </summary>
		[JsonProperty("Element9210")]
		public Element9210 element9210 { get; set; }

		/// <summary>
		/// Representeert Element9211
		/// Officiële gemeentenaam
		/// </summary>
		[JsonProperty("Element9211")]
		public Element9211 element9211 { get; set; }

		/// <summary>
		/// Representeert Element9212
		/// Nieuwe gemeentecode
		/// </summary>
		[JsonProperty("Element9212")]
		public Element9212 element9212 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public string Code => element9210.Waarde;

		[JsonIgnore]
		public string Omschrijving => element9211.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel33(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element9210 = new Element9210(columns[0]);
			element9211 = new Element9211(columns[1]);
			element9212 = new Element9212(columns[2]);
			element9998 = new Element9998(columns[3]);
			element9999 = new Element9999(columns[4]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel34(Landentabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel34
	{
		/// <summary>
		/// Representeert Element9410
		/// Landcode
		/// </summary>
		[JsonProperty("Element9410")]
		public Element9410 element9410 { get; set; }

		/// <summary>
		/// Representeert Element9411
		/// Officiële landnaam
		/// </summary>
		[JsonProperty("Element9411")]
		public Element9411 element9411 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public Int16 Code => element9410.Waarde;

		[JsonIgnore]
		public string Omschrijving => element9411.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel34(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element9410 = new Element9410(columns[0]);
			element9411 = new Element9411(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel36(Voorvoegseltabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel36
	{
		/// <summary>
		/// Representeert Element0231
		/// Voorvoegsel
		/// </summary>
		[JsonProperty("Element0231")]
		public Element0231 element0231 { get; set; }

		[JsonIgnore]
		public String Code => element0231.Waarde;

		[JsonIgnore]
		public string Omschrijving => element0231.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel36(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element0231 = new Element0231(columns[0]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel37(Tabel Reden opnemen/beëindigen nationaliteit)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel37
	{
		/// <summary>
		/// Representeert Element9610
		/// Reden opnemen/beëindigen nationaliteit
		/// </summary>
		[JsonProperty("Element9610")]
		public Element9610 element9610 { get; set; }

		/// <summary>
		/// Representeert Element9620
		/// Omschrijving
		/// </summary>
		[JsonProperty("Element9620")]
		public Element9620 element9620 { get; set; }

		/// <summary>
		/// Representeert Element9630
		/// Soort
		/// </summary>
		[JsonProperty("Element9630")]
		public Element9630 element9630 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public Int16 Code => element9610.Waarde;

		[JsonIgnore]
		public string Omschrijving => element9620.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel37(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element9610 = new Element9610(columns[0]);
			element9620 = new Element9620(columns[1]);
			element9630 = new Element9630(columns[2]);
			element9998 = new Element9998(columns[3]);
			element9999 = new Element9999(columns[4]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel38(Tabel Adellijke titel/predicaat)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel38
	{
		/// <summary>
		/// Representeert Element0221
		/// Adellijke titel/predicaat
		/// </summary>
		[JsonProperty("Element0221")]
		public Element0221 element0221 { get; set; }

		/// <summary>
		/// Representeert Element0222
		/// Omschrijving adellijke titel/predicaat
		/// </summary>
		[JsonProperty("Element0222")]
		public Element0222 element0222 { get; set; }

		/// <summary>
		/// Representeert Element0223
		/// Soort
		/// </summary>
		[JsonProperty("Element0223")]
		public Element0223 element0223 { get; set; }

		[JsonIgnore]
		public String Code => element0221.Waarde;

		[JsonIgnore]
		public string Omschrijving => element0222.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel38(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element0221 = new Element0221(columns[0]);
			element0222 = new Element0222(columns[1]);
			element0223 = new Element0223(columns[2]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel39(Tabel Akteaanduiding)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel39
	{
		/// <summary>
		/// Representeert Element8121
		/// Akteaanduiding
		/// </summary>
		[JsonProperty("Element8121")]
		public Element8121 element8121 { get; set; }

		/// <summary>
		/// Representeert Element8122
		/// Omschrijving soort akte
		/// </summary>
		[JsonProperty("Element8122")]
		public Element8122 element8122 { get; set; }

		[JsonIgnore]
		public String Code => element8121.Waarde;

		[JsonIgnore]
		public string Omschrijving => element8122.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel39(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element8121 = new Element8121(columns[0]);
			element8122 = new Element8122(columns[1]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel41(Tabel Reden ontbinding/nietigverklaring huwelijk/geregistreerd partnerschap)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel41
	{
		/// <summary>
		/// Representeert Element0741
		/// Reden ontbinding/nietigverklaring huwelijk/geregistreerd
		/// </summary>
		[JsonProperty("Element0741")]
		public Element0741 element0741 { get; set; }

		/// <summary>
		/// Representeert Element0742
		/// Omschrijving
		/// </summary>
		[JsonProperty("Element0742")]
		public Element0742 element0742 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public String Code => element0741.Waarde;

		[JsonIgnore]
		public string Omschrijving => element0742.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel41(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element0741 = new Element0741(columns[0]);
			element0742 = new Element0742(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel48(Tabel Nederlands reisdocument)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel48
	{
		/// <summary>
		/// Representeert Element3511
		/// Nederlands reisdocument
		/// </summary>
		[JsonProperty("Element3511")]
		public Element3511 element3511 { get; set; }

		/// <summary>
		/// Representeert Element3512
		/// Omschrijving
		/// </summary>
		[JsonProperty("Element3512")]
		public Element3512 element3512 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public String Code => element3511.Waarde;

		[JsonIgnore]
		public string Omschrijving => element3512.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel48(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element3511 = new Element3511(columns[0]);
			element3512 = new Element3512(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel49(Tabel Autoriteit van afgifte Nederlands reisdocument)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel49
	{
		/// <summary>
		/// Representeert Element3541
		/// Autoriteit van afgifte
		/// </summary>
		[JsonProperty("Element3541")]
		public Element3541 element3541 { get; set; }

		/// <summary>
		/// Representeert Element3542
		/// Omschrijving
		/// </summary>
		[JsonProperty("Element3542")]
		public Element3542 element3542 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public String Code => element3541.Waarde;

		[JsonIgnore]
		public string Omschrijving => element3542.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel49(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element3541 = new Element3541(columns[0]);
			element3542 = new Element3542(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel56(Verblijfstiteltabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel56
	{
		/// <summary>
		/// Representeert Element3911
		/// Verblijfstitel
		/// </summary>
		[JsonProperty("Element3911")]
		public Element3911 element3911 { get; set; }

		/// <summary>
		/// Representeert Element3912
		/// Omschrijving
		/// </summary>
		[JsonProperty("Element3912")]
		public Element3912 element3912 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public Int16 Code => element3911.Waarde;

		[JsonIgnore]
		public string Omschrijving => element3912.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel56(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element3911 = new Element3911(columns[0]);
			element3912 = new Element3912(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel60(RNI-deelnemerstabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel60
	{
		/// <summary>
		/// Representeert Element8811
		/// Code RNI-deelnemer
		/// </summary>
		[JsonProperty("Element8811")]
		public Element8811 element8811 { get; set; }

		/// <summary>
		/// Representeert Element8812
		/// Omschrijving RNI-deelnemer
		/// </summary>
		[JsonProperty("Element8812")]
		public Element8812 element8812 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public Int16 Code => element8811.Waarde;

		[JsonIgnore]
		public string Omschrijving => element8812.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel60(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element8811 = new Element8811(columns[0]);
			element8812 = new Element8812(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
	///<summary>
	///Representeert een tabelregel uit Landelijke Tabel61(Gezagsverhoudingtabel)
	///</summary>
	[ExcludeFromCodeCoverage]
	public sealed partial class Tabelregel61
	{
		/// <summary>
		/// Representeert Element3211
		/// Gezagsverhouding
		/// </summary>
		[JsonProperty("Element3211")]
		public Element3211 element3211 { get; set; }

		/// <summary>
		/// Representeert Element3212
		/// Omschrijving
		/// </summary>
		[JsonProperty("Element3212")]
		public Element3212 element3212 { get; set; }

		/// <summary>
		/// Representeert Element9998
		/// Datum ingang tabelregel
		/// </summary>
		[JsonProperty("Element9998")]
		public Element9998 element9998 { get; set; }

		/// <summary>
		/// Representeert Element9999
		/// Datum beëindiging tabelregel
		/// </summary>
		[JsonProperty("Element9999")]
		public Element9999 element9999 { get; set; }

		[JsonIgnore]
		public String Code => element3211.Waarde;

		[JsonIgnore]
		public string Omschrijving => element3212.Waarde;

			/// <summary>
		/// Constructor
		/// </summary>
		public Tabelregel61(string rgl)
		{
			string[] columns = rgl.Split(new char[] { '•' }, StringSplitOptions.None);
			element3211 = new Element3211(columns[0]);
			element3212 = new Element3212(columns[1]);
			element9998 = new Element9998(columns[2]);
			element9999 = new Element9999(columns[3]);
		}

	}
}
