//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template: Logisch Ontwerp BRP 4.2.0 1 januari 2023
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;

namespace Centric.PIV.Burgerzaken.RaadplegenPL.ResourceLayer.Brp.DomainModel.LogischOntwerp
{
	/// <summary>
	/// Representeert Categorie01/51 (Persoon)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie01Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 01 (Identificatienummers)
		/// </summary>
		[JsonProperty("Identificatienummers")]
		public Groep01 groep01 { get; set; }

		/// <summary>
		/// Representeert Groep 02 (Naam)
		/// </summary>
		[JsonProperty("Naam")]
		public Groep02 groep02 { get; set; }

		/// <summary>
		/// Representeert Groep 03 (Geboorte)
		/// </summary>
		[JsonProperty("Geboorte")]
		public Groep03 groep03 { get; set; }

		/// <summary>
		/// Representeert Groep 04 (Geslacht)
		/// </summary>
		[JsonProperty("Geslacht")]
		public Groep04 groep04 { get; set; }

		/// <summary>
		/// Representeert Groep 20 (A-nummerverwijzingen)
		/// </summary>
		[JsonProperty("A-nummerverwijzingen")]
		public Groep20 groep20 { get; set; }

		/// <summary>
		/// Representeert Groep 61 (Naamgebruik)
		/// </summary>
		[JsonProperty("Naamgebruik")]
		public Groep61 groep61 { get; set; }

		/// <summary>
		/// Representeert Groep 81 (Akte)
		/// </summary>
		[JsonProperty("Akte")]
		public Groep81 groep81 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (RNI-deelnemer)
		/// </summary>
		[JsonProperty("RNI-deelnemer")]
		public Groep88 groep88 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie02/52 (Ouder1)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie02Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 01 (Identificatienummers)
		/// </summary>
		[JsonProperty("Identificatienummers")]
		public Groep01 groep01 { get; set; }

		/// <summary>
		/// Representeert Groep 02 (Naam)
		/// </summary>
		[JsonProperty("Naam")]
		public Groep02 groep02 { get; set; }

		/// <summary>
		/// Representeert Groep 03 (Geboorte)
		/// </summary>
		[JsonProperty("Geboorte")]
		public Groep03 groep03 { get; set; }

		/// <summary>
		/// Representeert Groep 04 (Geslacht)
		/// </summary>
		[JsonProperty("Geslacht")]
		public Groep04 groep04 { get; set; }

		/// <summary>
		/// Representeert Groep 62 (Familierechtelijke betrekking)
		/// </summary>
		[JsonProperty("Familierechtelijke betrekking")]
		public Groep62 groep62 { get; set; }

		/// <summary>
		/// Representeert Groep 81 (Akte)
		/// </summary>
		[JsonProperty("Akte")]
		public Groep81 groep81 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie03/53 (Ouder2)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie03Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 01 (Identificatienummers)
		/// </summary>
		[JsonProperty("Identificatienummers")]
		public Groep01 groep01 { get; set; }

		/// <summary>
		/// Representeert Groep 02 (Naam)
		/// </summary>
		[JsonProperty("Naam")]
		public Groep02 groep02 { get; set; }

		/// <summary>
		/// Representeert Groep 03 (Geboorte)
		/// </summary>
		[JsonProperty("Geboorte")]
		public Groep03 groep03 { get; set; }

		/// <summary>
		/// Representeert Groep 04 (Geslacht)
		/// </summary>
		[JsonProperty("Geslacht")]
		public Groep04 groep04 { get; set; }

		/// <summary>
		/// Representeert Groep 62 (Familierechtelijke betrekking)
		/// </summary>
		[JsonProperty("Familierechtelijke betrekking")]
		public Groep62 groep62 { get; set; }

		/// <summary>
		/// Representeert Groep 81 (Akte)
		/// </summary>
		[JsonProperty("Akte")]
		public Groep81 groep81 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie04/54 (Nationaliteit)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie04Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 05 (Nationaliteit)
		/// </summary>
		[JsonProperty("Nationaliteit")]
		public Groep05 groep05 { get; set; }

		/// <summary>
		/// Representeert Groep 63 (Opnemen nationaliteit)
		/// </summary>
		[JsonProperty("Opnemen nationaliteit")]
		public Groep63 groep63 { get; set; }

		/// <summary>
		/// Representeert Groep 64 (Beëindigen nationaliteit)
		/// </summary>
		[JsonProperty("Beëindigen nationaliteit")]
		public Groep64 groep64 { get; set; }

		/// <summary>
		/// Representeert Groep 65 (Bijzonder Nederlanderschap)
		/// </summary>
		[JsonProperty("Bijzonder Nederlanderschap")]
		public Groep65 groep65 { get; set; }

		/// <summary>
		/// Representeert Groep 73 (Buitenlands persoonsnummer)
		/// </summary>
		[JsonProperty("Buitenlands persoonsnummer")]
		public Groep73 groep73 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (RNI-deelnemer)
		/// </summary>
		[JsonProperty("RNI-deelnemer")]
		public Groep88 groep88 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie05/55 (Huwelijk/geregistreerd)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie05Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 01 (Identificatienummers)
		/// </summary>
		[JsonProperty("Identificatienummers")]
		public Groep01 groep01 { get; set; }

		/// <summary>
		/// Representeert Groep 02 (Naam)
		/// </summary>
		[JsonProperty("Naam")]
		public Groep02 groep02 { get; set; }

		/// <summary>
		/// Representeert Groep 03 (Geboorte)
		/// </summary>
		[JsonProperty("Geboorte")]
		public Groep03 groep03 { get; set; }

		/// <summary>
		/// Representeert Groep 04 (Geslacht)
		/// </summary>
		[JsonProperty("Geslacht")]
		public Groep04 groep04 { get; set; }

		/// <summary>
		/// Representeert Groep 06 (Huwelijkssluiting/aangaan geregistreerd partnerschap)
		/// </summary>
		[JsonProperty("Huwelijkssluiting/aangaan geregistreerd partnerschap")]
		public Groep06 groep06 { get; set; }

		/// <summary>
		/// Representeert Groep 07 (Ontbinding huwelijk/geregistreerd partnerschap)
		/// </summary>
		[JsonProperty("Ontbinding huwelijk/geregistreerd partnerschap")]
		public Groep07 groep07 { get; set; }

		/// <summary>
		/// Representeert Groep 15 (Soort verbintenis)
		/// </summary>
		[JsonProperty("Soort verbintenis")]
		public Groep15 groep15 { get; set; }

		/// <summary>
		/// Representeert Groep 81 (Akte)
		/// </summary>
		[JsonProperty("Akte")]
		public Groep81 groep81 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie06/56 (Overlijden)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie06Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 08 (Overlijden)
		/// </summary>
		[JsonProperty("Overlijden")]
		public Groep08 groep08 { get; set; }

		/// <summary>
		/// Representeert Groep 81 (Akte)
		/// </summary>
		[JsonProperty("Akte")]
		public Groep81 groep81 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (RNI-deelnemer)
		/// </summary>
		[JsonProperty("RNI-deelnemer")]
		public Groep88 groep88 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie07/57 (Inschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie07Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 66 (Blokkering)
		/// </summary>
		[JsonProperty("Blokkering")]
		public Groep66 groep66 { get; set; }

		/// <summary>
		/// Representeert Groep 67 (Opschorting)
		/// </summary>
		[JsonProperty("Opschorting")]
		public Groep67 groep67 { get; set; }

		/// <summary>
		/// Representeert Groep 68 (Opname)
		/// </summary>
		[JsonProperty("Opname")]
		public Groep68 groep68 { get; set; }

		/// <summary>
		/// Representeert Groep 69 (Gemeente PK)
		/// </summary>
		[JsonProperty("Gemeente PK")]
		public Groep69 groep69 { get; set; }

		/// <summary>
		/// Representeert Groep 70 (Geheim)
		/// </summary>
		[JsonProperty("Geheim")]
		public Groep70 groep70 { get; set; }

		/// <summary>
		/// Representeert Groep 71 (Verificatie)
		/// </summary>
		[JsonProperty("Verificatie")]
		public Groep71 groep71 { get; set; }

		/// <summary>
		/// Representeert Groep 80 (Synchroniciteit)
		/// </summary>
		[JsonProperty("Synchroniciteit")]
		public Groep80 groep80 { get; set; }

		/// <summary>
		/// Representeert Groep 87 (PK-conversie)
		/// </summary>
		[JsonProperty("PK-conversie")]
		public Groep87 groep87 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (RNI-deelnemer)
		/// </summary>
		[JsonProperty("RNI-deelnemer")]
		public Groep88 groep88 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie08/58 (Verblijfplaats)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie08Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 09 (Gemeente)
		/// </summary>
		[JsonProperty("Gemeente")]
		public Groep09 groep09 { get; set; }

		/// <summary>
		/// Representeert Groep 10 (Adreshouding)
		/// </summary>
		[JsonProperty("Adreshouding")]
		public Groep10 groep10 { get; set; }

		/// <summary>
		/// Representeert Groep 11 (Adres)
		/// </summary>
		[JsonProperty("Adres")]
		public Groep11 groep11 { get; set; }

		/// <summary>
		/// Representeert Groep 12 (Locatie)
		/// </summary>
		[JsonProperty("Locatie")]
		public Groep12 groep12 { get; set; }

		/// <summary>
		/// Representeert Groep 13 (Adres buitenland)
		/// </summary>
		[JsonProperty("Adres buitenland")]
		public Groep13 groep13 { get; set; }

		/// <summary>
		/// Representeert Groep 14 (Immigratie)
		/// </summary>
		[JsonProperty("Immigratie")]
		public Groep14 groep14 { get; set; }

		/// <summary>
		/// Representeert Groep 72 (Adresaangifte)
		/// </summary>
		[JsonProperty("Adresaangifte")]
		public Groep72 groep72 { get; set; }

		/// <summary>
		/// Representeert Groep 75 (Documentindicatie)
		/// </summary>
		[JsonProperty("Documentindicatie")]
		public Groep75 groep75 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (RNI-deelnemer)
		/// </summary>
		[JsonProperty("RNI-deelnemer")]
		public Groep88 groep88 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie09/59 (Kind)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie09Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 01 (Identificatienummers)
		/// </summary>
		[JsonProperty("Identificatienummers")]
		public Groep01 groep01 { get; set; }

		/// <summary>
		/// Representeert Groep 02 (Naam)
		/// </summary>
		[JsonProperty("Naam")]
		public Groep02 groep02 { get; set; }

		/// <summary>
		/// Representeert Groep 03 (Geboorte)
		/// </summary>
		[JsonProperty("Geboorte")]
		public Groep03 groep03 { get; set; }

		/// <summary>
		/// Representeert Groep 81 (Akte)
		/// </summary>
		[JsonProperty("Akte")]
		public Groep81 groep81 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }

		/// <summary>
		/// Representeert Groep 89 (Registratie afstamming)
		/// </summary>
		[JsonProperty("Registratie afstamming")]
		public Groep89 groep89 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie10/60 (Verblijfstitel)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie10Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 39 (Verblijfstitel)
		/// </summary>
		[JsonProperty("Verblijfstitel")]
		public Groep39 groep39 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie11/61 (Gezagsverhouding)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie11Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 32 (Gezag minderjarige)
		/// </summary>
		[JsonProperty("Gezag minderjarige")]
		public Groep32 groep32 { get; set; }

		/// <summary>
		/// Representeert Groep 33 (Curatele)
		/// </summary>
		[JsonProperty("Curatele")]
		public Groep33 groep33 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie12/62 (Reisdocument)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie12Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 35 (Nederlands reisdocument)
		/// </summary>
		[JsonProperty("Nederlands reisdocument")]
		public Groep35 groep35 { get; set; }

		/// <summary>
		/// Representeert Groep 36 (Signalering)
		/// </summary>
		[JsonProperty("Signalering")]
		public Groep36 groep36 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie13/63 (Kiesrecht)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie13Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 31 (Europees kiesrecht)
		/// </summary>
		[JsonProperty("Europees kiesrecht")]
		public Groep31 groep31 { get; set; }

		/// <summary>
		/// Representeert Groep 38 (Uitsluiting kiesrecht)
		/// </summary>
		[JsonProperty("Uitsluiting kiesrecht")]
		public Groep38 groep38 { get; set; }

		/// <summary>
		/// Representeert Groep 82 (Document)
		/// </summary>
		[JsonProperty("Document")]
		public Groep82 groep82 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie14/64 (Afnemersindicatie)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie14Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 40 (Afnemer)
		/// </summary>
		[JsonProperty("Afnemer")]
		public Groep40 groep40 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie16/66 (Tijdelijk)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie16Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 09 (Gemeente)
		/// </summary>
		[JsonProperty("Gemeente")]
		public Groep09 groep09 { get; set; }

		/// <summary>
		/// Representeert Groep 11 (Adres)
		/// </summary>
		[JsonProperty("Adres")]
		public Groep11 groep11 { get; set; }

		/// <summary>
		/// Representeert Groep 18 (Einde geldigheid)
		/// </summary>
		[JsonProperty("Einde geldigheid")]
		public Groep18 groep18 { get; set; }

		/// <summary>
		/// Representeert Groep 19 (Adrestype)
		/// </summary>
		[JsonProperty("Adrestype")]
		public Groep19 groep19 { get; set; }

		/// <summary>
		/// Representeert Groep 72 (Adresaangifte)
		/// </summary>
		[JsonProperty("Adresaangifte")]
		public Groep72 groep72 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (Deelnemer)
		/// </summary>
		[JsonProperty("Deelnemer")]
		public Groep88 groep88 { get; set; }

		/// <summary>
		/// Representeert Groep  ()
		/// </summary>
		[JsonProperty("")]
		public Groep groep { get; set; }
	}

	/// <summary>
	/// Representeert Categorie17/67 (Contactgegevens)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie17Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 16 (Telefoon)
		/// </summary>
		[JsonProperty("Telefoon")]
		public Groep16 groep16 { get; set; }

		/// <summary>
		/// Representeert Groep 17 (E-mail)
		/// </summary>
		[JsonProperty("E-mail")]
		public Groep17 groep17 { get; set; }

		/// <summary>
		/// Representeert Groep 88 (Deelnemer)
		/// </summary>
		[JsonProperty("Deelnemer")]
		public Groep88 groep88 { get; set; }

		/// <summary>
		/// Representeert Groep  ()
		/// </summary>
		[JsonProperty("")]
		public Groep groep { get; set; }
	}

	/// <summary>
	/// Representeert Categorie21/71 (Verwijzing)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie21Base : CategorieBase
	{
		/// <summary>
		/// Representeert Groep 01 (Identificatienummers)
		/// </summary>
		[JsonProperty("Identificatienummers")]
		public Groep01 groep01 { get; set; }

		/// <summary>
		/// Representeert Groep 02 (Naam)
		/// </summary>
		[JsonProperty("Naam")]
		public Groep02 groep02 { get; set; }

		/// <summary>
		/// Representeert Groep 03 (Geboorte)
		/// </summary>
		[JsonProperty("Geboorte")]
		public Groep03 groep03 { get; set; }

		/// <summary>
		/// Representeert Groep 09 (Gemeente)
		/// </summary>
		[JsonProperty("Gemeente")]
		public Groep09 groep09 { get; set; }

		/// <summary>
		/// Representeert Groep 70 (Geheim)
		/// </summary>
		[JsonProperty("Geheim")]
		public Groep70 groep70 { get; set; }

		/// <summary>
		/// Representeert Groep 83 (Procedure)
		/// </summary>
		[JsonProperty("Procedure")]
		public Groep83 groep83 { get; set; }

		/// <summary>
		/// Representeert Groep 85 (Geldigheid)
		/// </summary>
		[JsonProperty("Geldigheid")]
		public Groep85 groep85 { get; set; }

		/// <summary>
		/// Representeert Groep 86 (Opneming)
		/// </summary>
		[JsonProperty("Opneming")]
		public Groep86 groep86 { get; set; }
	}

}
