//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template: Logisch Ontwerp BRP 4.2.0 1 januari 2023
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;

namespace Centric.PIV.Burgerzaken.RaadplegenPL.ResourceLayer.Brp.DomainModel.LogischOntwerp
{
	/// <summary>
	/// Representeert Categorie07 (Inschrijving)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public class Categorie07 : Categorie07Base
	{
	}

	/// <summary>
	/// Representeert Categorie12 (Reisdocument)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public class Categorie12 : Categorie12Base
	{
	}

	/// <summary>
	/// Representeert Categorie13 (Kiesrecht)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public class Categorie13 : Categorie13Base
	{
	}

	/// <summary>
	/// Representeert Categorie17 (Contactgegevens)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public class Categorie17 : Categorie17Base
	{
	}

}
