//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template: Logisch Ontwerp BRP 4.2.0 1 januari 2023
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;

namespace Centric.PIV.Burgerzaken.RaadplegenPL.ResourceLayer.Brp.DomainModel.LogischOntwerp
{
	/// <summary>
	/// Representeert Categorie51 (Historie Persoon)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie51 : Categorie01Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie52 (Historie Ouder1)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie52 : Categorie02Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie53 (Historie Ouder2)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie53 : Categorie03Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie54 (Historie Nationaliteit)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie54 : Categorie04Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie55 (Historie Huwelijk/geregistreerd)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie55 : Categorie05Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie56 (Historie Overlijden)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie56 : Categorie06Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie58 (Historie Verblijfplaats)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie58 : Categorie08Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie59 (Historie Kind)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie59 : Categorie09Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie60 (Historie Verblijfstitel)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie60 : Categorie10Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie61 (Historie Gezagsverhouding)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie61 : Categorie11Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie64 (Historie Afnemersindicatie)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie64 : Categorie14Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie66 (Historie Tijdelijk)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie66 : Categorie16Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

	/// <summary>
	/// Representeert Categorie71 (Historie Verwijzing)
	/// </summary>
	[ExcludeFromCodeCoverage]
	public abstract class Categorie71 : Categorie21Base
	{
		/// <summary>
		/// Representeert Groep 84 (Onjuist)
		/// </summary>
		[JsonProperty("Onjuist")]
		public Groep84 groep84 { get; set; }
	}

}
